development:
  host: localhost
  database: localcrud_development

test:
  host: localhost
  database: localcrud_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
